### ISSUE TITLE
MASA-求助

### ISSUE THREAD

**Issue by lrhgogogo** [SteamerLee/MASA#10]
尊敬的MASA作者：

       您好！我是一名MASA项目的忠实follower，仔细阅读您分享的文章与代码后，您在DRL in Potfolio Management方面的创新思路让我受益匪浅，您在issue中的耐心回复也对我帮助莫大。这或许有些冒犯，但我诚恳地向您询问，是否能为我（rhluo366@gmail.com）提供文中benchmark对应的test_stepdata.xlsx以帮助我绘制参照图，我一定承诺在使用过程中严格遵守科研伦理、尊重您的科研成果。若出于版权或隐私考虑不便提供，我完全可以理解，我仍然对您表达万分的感谢！

       感谢您在百忙之中阅读我的Issue！祝您身体健康，生活愉快！

**Comment by SteamerLee** [comment]
您好，已回复邮件。十分感谢您的关注，谢谢！
