### ISSUE TITLE
tic chosen

### ISSUE THREAD

**Issue by lrhgogogo** [SteamerLee/MASA#5]
If it's convenient, could you tell me which specific stocks were chosen in each market?

**Comment by SteamerLee** [comment]
Here are the samples for your reference:
Dow Jones: UNH, GS, HD, MSFT, MCD, AMGN, V, CRM, CAT, HON;
S&P 500: AAPL, MSFT, AMZN, GOOGL, TSLA, UNH, NVDA, JNJ, META, XOM;
CSI300: 600519.XSHG, 601318.XSHG, 600036.XSHG, 000858.XSHE, 601166.XSHG, 002594.XSHE, 600030.XSHG, 600900.XSHG, 601899.XSHG, 300059.XSHE.

Thank you for your kind attention!

**Comment by lrhgogogo** [comment]
Thanks a lot!!!
