### ISSUE TITLE
CBF Issue

### ISSUE THREAD

**Issue by lrhgogogo** [SteamerLee/MASA#9]
![image](https://github.com/user-attachments/assets/d27763f6-fef8-4a14-a08b-d020dae1556c)
![image](https://github.com/user-attachments/assets/1265303f-c66b-4453-a3fe-0187ed3503b0)

不好意思再次打扰您，我想向您请教关于controllers.py中cbf_opt()的问题，当设置gamma=0.7<1时，当前风险剩余裕度last_h_risk越大，反而会使得安全阈值socp_d越小，是不是有一点神奇？

Please feel free to respond at your convenience. I truly appreciate your valuable time. Thank you!

**Comment by SteamerLee** [comment]
您好，gamma的取值范围是[0, 1], 当gamma越大（接近1）时，对于风险的约束会变小，即安全阈值更大，可接受更大的风险，并且当gamma=1时会退化为普通的风险约束。另一方面，当gamma越小(接近0)时，风险约束会变严格，对风险要求更高。这部分推导是与control theory中的barrier function有关。谢谢！
